import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <div className="w-full min-h-screen flex flex-col sm:px-6 md:px-[114px]">
          <div className="mx-auto w-full h-full sm:max-w-[1142px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
